/* Dar Mama — interactions + EN/FR i18n
   English is the default (and the source for SEO). The switch only
   changes on-page visible text via [data-i18n] / [data-i18n-ph]. */

var DICT = {
  en: {
    /* common */
    nav_home:"Home", nav_platform:"Owner Platform", nav_services:"Services", nav_about:"About", nav_contact:"Contact",
    nav_login:"Owner Login", nav_estimate:"Free revenue estimate",
    foot_about:"Where hospitality meets care. Transparent short-term rental management in Dubai, with a real-time platform built for owners.",
    foot_h_company:"Company", foot_h_owners:"Owners", foot_h_contact:"Contact",
    foot_about_us:"About us", foot_services:"Services", foot_platform:"Owner platform", foot_contact:"Contact",
    foot_estimate:"Free revenue estimate", foot_login:"Owner login", foot_how:"How the platform works",
    foot_rights:"© 2026 Dar Mama. All rights reserved.", foot_loc:"Dubai, United Arab Emirates · DET holiday homes (formerly DTCM)",
    wa_chat:"Chat",
    /* home */
    h_eyebrow:"Short-term rental management · Dubai",
    h_h1:'Own the property.<br><span class="accent">See</span> the performance.',
    h_sub:"Dar Mama manages your Dubai short-term rental end to end — completely hassle-free — and gives you a real-time owner platform to watch every booking, every dirham, every payout. Hospitality with care, run like a hotel.",
    h_cta1:"Get a free revenue estimate", h_cta2:"See the owner platform",
    h_trust_s1:"Superhost · 2 years", h_trust_s2:"Transparent commission", h_trust_s3:"Licensed holiday homes",
    h_sv_eyebrow:"What we do", h_sv_title:"Full management, maximised revenue",
    h_sv_lead:"From listing and pricing to check-ins, cleaning and maintenance — we run your property like an asset, not a side gig.",
    h_c1_t:"Revenue management", h_c1_b:"Dynamic, data-driven pricing the way hotels do it — optimising occupancy and ADR to lift your RevPAR, never just chasing volume.",
    h_c2_t:"Full property management", h_c2_b:"Listings, bookings, guest screening, check-in and check-out, cleaning, linen and maintenance — handled, so you don't lift a finger.",
    h_c3_t:"Personalised guest care", h_c3_b:"24/7 multilingual communication on the channel guests prefer, including WhatsApp, with our team handling in-person check-ins whenever they're needed.",
    h_c4_t:"Transparent finance", h_c4_b:"A clear 17% commission on your net revenue, and a monthly statement that itemises gross, OTA fees, cleaning, tourism dirham and your net payout. No surprises, ever.",
    h_c5_t:"Maintenance & upkeep", h_c5_b:"We keep your property in top shape with trusted contractors and document the work — protecting your asset and your reviews.",
    h_c6_t:"Licensing & compliance", h_c6_b:"We guide DET holiday-home registration (formerly DTCM) and keep your unit compliant, so it's rented legally and worry-free.",
    h_op_eyebrow:"The Dar Mama difference", h_op_title:"The only Dubai manager that shows you everything, live.",
    h_op_sub:"Most owners hand over their keys and wait for a vague monthly email. With Dar Mama you get a secure owner platform — the same numbers we work from, available to you 24/7.",
    h_op_li0:"We handle everything — completely hassle-free for you",
    h_op_li1:"Real-time occupancy, ADR, RevPAR and revenue per property",
    h_op_li2:"Monthly statements with every line item and your exact net payout",
    h_op_li3:"Past, present and upcoming reservations at a glance",
    h_op_li4:"Your documents, licences and invoices in one secure vault",
    h_op_li5:"Bilingual, desktop and mobile, accessible anywhere",
    h_op_cta1:"Explore the platform", h_op_cta2:"Owner login",
    h_hw_eyebrow:"How it works", h_hw_title:"From keys to payouts in four steps",
    h_hw1_t:"Free estimate", h_hw1_b:"Tell us your unit and area. We send a data-backed revenue projection — no obligation.",
    h_hw2_t:"Onboarding", h_hw2_b:"We photograph, list, price and license your property, and set up your owner account.",
    h_hw3_t:"We operate", h_hw3_b:"Bookings, guests, cleaning and maintenance run on autopilot, optimised daily.",
    h_hw4_t:"You get paid", h_hw4_b:"Track everything live and receive a clear statement and payout each month.",
    h_st1:"Guest support", h_st2:"Superhost rating", h_st3:"Owner reporting", h_st4:"Commission, all-in",
    h_tm_eyebrow:"Owners say",
    h_tm_q:"\"For the first time I can actually see what my apartment is doing — bookings, revenue, payouts, all in one place. It feels like having a hotel team and a finance department in my pocket.\"",
    h_tm_who:"— David, a Dar Mama property owner, Downtown Dubai",
    h_faq_eyebrow:"FAQ", h_faq_title:"Questions owners ask",
    h_q1:"How much can I earn renting my apartment in Dubai?",
    h_a1:"It depends on the area, size and finish of your property. We provide a free, data-backed revenue estimate based on the real performance of comparable units in your building or neighbourhood.",
    h_q2:"What does Dar Mama charge?",
    h_a2:"A simple, transparent 17% fee — and only on your NET revenue. \"Net\" means what's left after the booking platform's own commission, the cleaning fee and the Dubai tourism tax are deducted from the gross booking amount. Our 17% applies to that net base, and every line is laid out in your monthly statement so you can see exactly how your payout is built.",
    h_q3:"Can I see my property's performance in real time?",
    h_a3:"Yes. Every owner gets a secure login to the Dar Mama owner platform with live occupancy, ADR, RevPAR, revenue, statements and documents.",
    h_q4:"Do you handle the Dubai holiday home licence?",
    h_a4:"Yes. We guide you through DET holiday-home registration (formerly DTCM) and handle operational compliance so your unit is rented legally.",
    h_cta_eyebrow:"Ready when you are", h_cta_title:"See what your property could earn",
    h_cta_sub:"Get a free, no-obligation revenue estimate and a tour of the owner platform.",
    h_cta_b1:"Get my free estimate", h_cta_b2:"WhatsApp us",
    /* owner platform page */
    opp_eyebrow:"Your property, in real time", opp_h1:"The owner platform that makes management transparent",
    opp_sub:"Other managers send a vague email once a month. Dar Mama gives you a secure login to the exact dashboard we work from — live performance, statements and documents, on desktop and mobile.",
    opp_login:"Owner login", opp_become:"Become an owner",
    opp_eyebrow2:"Built for revenue management", opp_t2:"The same numbers we optimise — visible to you",
    opp_p2:"We run your property with hotel-grade revenue management: occupancy, ADR and RevPAR tracked daily. The owner platform surfaces those exact KPIs so you always know how your asset is performing — and can see the result of every pricing decision.",
    opp_li1:"Occupancy, ADR and RevPAR with month-on-month and year-on-year change",
    opp_li2:"Revenue by channel — Airbnb, Booking.com, Expedia, direct",
    opp_li3:"Forecast and seasonality so there are no surprises",
    opp_inside_eyebrow:"What's inside", opp_inside_title:"Everything an owner needs, in one place",
    opp_f1_t:"Live performance", opp_f1_b:"Occupancy, ADR, RevPAR, gross and net revenue, updated from your bookings — per property and across your portfolio.",
    opp_f2_t:"Monthly statements", opp_f2_b:"Every line item: gross, OTA commission, cleaning, tourism dirham, our 17% fee and your exact net payout. Download as PDF.",
    opp_f3_t:"Reservations", opp_f3_b:"Past, ongoing and upcoming stays, channels, nights and guest reviews — with a clear monthly calendar.",
    opp_f4_t:"Payout history", opp_f4_b:"See what's been paid and what's coming, with a transparent record of every transfer.",
    opp_f5_t:"Document vault", opp_f5_b:"Licences, contracts, invoices and reports stored securely and accessible whenever you need them.",
    opp_f6_t:"Private & secure", opp_f6_b:"You see only your own properties. Bank-grade access control, two-factor authentication and encrypted data.",
    opp_why_eyebrow:"Why it matters", opp_why_title:"Transparency is the difference between a manager and a partner",
    opp_why_p:"When you can see everything, trust isn't a promise — it's a dashboard. No chasing for updates, no opaque statements, no wondering where your money went. Just clear numbers you can check any time, from anywhere.",
    opp_why_li1:"Desktop-first, fully mobile, installable like an app",
    opp_why_li2:"Bilingual interface, currency in AED",
    opp_why_li3:"One login for your whole portfolio",
    opp_why_b1:"Get started", opp_why_b2:"See our services",
    opp_panel_big:"Live", opp_panel_small:"Your dashboard, on every device",
    opp_cta_eyebrow:"Already an owner?", opp_cta_title:"Log in to your platform",
    opp_cta_sub:"Access your live dashboard, statements and documents.",
    opp_cta_b1:"Owner login", opp_cta_b2:"Talk to us",
    /* services page */
    svp_eyebrow:"Full-service management · Dubai", svp_h1:"Everything your short-term rental needs — handled",
    svp_sub:"One partner for revenue, operations, guests and compliance. You keep ownership and full visibility; we do the work. It's completely hassle-free.",
    svp_cta1:"Get a free revenue estimate",
    svp_c1_t:"Revenue management", svp_c1_b:"Hotel-grade, data-driven pricing. We adjust rates daily by season, demand, events and competitor performance to maximise RevPAR — the balance of occupancy and rate — not just fill nights cheaply.",
    svp_c2_t:"Listings & distribution", svp_c2_b:"Professional listings on Airbnb, Booking.com, Expedia and direct, with quality photography, optimised copy and synced calendars to avoid double-bookings.",
    svp_c3_t:"Guest experience", svp_c3_b:"24/7 multilingual communication, screening, smooth check-in and check-out, and on-stay care — with our team handling in-person check-ins whenever needed. Great stays earn rave reviews.",
    svp_c4_t:"Housekeeping & linen", svp_c4_b:"Hotel-standard cleaning, fresh linen and amenities between every stay, with quality checks so your property is always guest-ready.",
    svp_c5_t:"Maintenance & upkeep", svp_c5_b:"Proactive maintenance with trusted contractors, documented before/after, protecting your asset and preventing bad reviews.",
    svp_c6_t:"Licensing & compliance", svp_c6_b:"Guidance through DET holiday-home registration (formerly DTCM) and ongoing compliance, so your unit is rented legally and safely.",
    svp_c7_t:"Transparent finance", svp_c7_b:"A clear 17% commission on net revenue, with monthly statements and on-time payouts — every fee and cost itemised in your owner platform. No hidden charges.",
    svp_c8_t:"Owner reporting", svp_c8_b:"Your real-time dashboard: occupancy, ADR, RevPAR, revenue, statements and documents — the feature competitors don't offer.",
    svp_rm_eyebrow:"Why revenue management matters", svp_rm_t:"We run your apartment like a hotel runs a room",
    svp_rm_p:"Most owners — and many managers — price a property and forget it. We treat every night as inventory to be sold at the right price. By optimising occupancy and ADR together, we lift RevPAR, the metric that actually reflects how hard your asset is working.",
    svp_rm_li1:"Daily dynamic pricing by demand, season and local events",
    svp_rm_li2:"Length-of-stay and minimum-night strategies",
    svp_rm_li3:"Channel mix optimisation to cut OTA fees",
    svp_rm_li4:"Forecasting so you can plan around seasonality",
    svp_cta_eyebrow:"Let's talk numbers", svp_cta_t:"What could your property earn with Dar Mama?",
    svp_cta_sub:"Free, no-obligation estimate based on real data from comparable Dubai units.",
    svp_cta_b1:"Get my free estimate", svp_cta_b2:"See the owner platform",
    /* about page */
    abp_eyebrow:"Where hospitality meets care", abp_h1:"Embrace the mama",
    abp_sub:"We don't just manage properties. We craft moments of comfort and luxury for your guests, and we treat your asset — and your trust — with the care it deserves.",
    abp_story_eyebrow:"Our story", abp_story_t:"A Dubai host's care, with a manager's discipline",
    abp_story_p1:"Dar Mama was founded on a simple belief: short-term rental owners deserve both peace of mind and the truth. Dubai's market is competitive and fast-moving, and too many owners hand over their keys only to receive vague updates and opaque statements.",
    abp_story_p2:"We built Dar Mama to be different — combining warm, attentive hospitality with the rigour of hotel-grade revenue management, and backing it with something almost no competitor offers: a real-time platform where you can see exactly how your property is performing, any time.",
    abp_panel_big:"4.97★", abp_panel_small:"Superhost · 2 years on Airbnb",
    abp_team_eyebrow:"The founders", abp_team_title:"Two operators, one standard of care",
    abp_team_intro:"Dar Mama isn't a faceless agency. It's two people who have spent their careers in hospitality and decided to do it properly — for owners like you.",
    abp_ismail_role:"Co-founder · Commercial, Marketing & Revenue Management",
    abp_ismail_bio:"Ismail spent 15 years inside the world's most demanding hospitality groups — Marriott, Accor and Disney — leading commercial, marketing and revenue management teams. There he learned how great hotels turn data into the right price at the right moment, and what true service really feels like. He founded Dar Mama to bring that same discipline to individual owners: every apartment priced and run like a hotel room, every decision backed by numbers you can actually see.",
    abp_dounia_role:"Co-founder · Customer Success & Operations",
    abp_dounia_bio:"Dounia has called Dubai home for 12 years, building her career in customer success and on-the-ground operations. She has overseen countless renovation and upgrade projects — turning tired apartments into homes guests rave about and owners are proud of. Warm with guests and relentless on detail, she makes sure every Dar Mama property looks and feels its best, stay after stay.",
    abp_commit_eyebrow:"What we stand for", abp_commit_title:"Our commitment to owners",
    abp_c1_t:"Total transparency", abp_c1_b:"You see the same numbers we do. Every booking, fee and payout is visible in your owner platform — no black box.",
    abp_c2_t:"Genuine care", abp_c2_b:"Every guest is unique, and so is every owner. We deliver personalised attention that earns rave reviews and lasting trust.",
    abp_c3_t:"Hospitality excellence", abp_c3_b:"We're your partner in crafting exceptional stays — protecting your reputation and your returns at the same time.",
    abp_q:"\"Your success is our success — and we're here to make it extraordinary.\"", abp_q_who:"— The Dar Mama team",
    abp_cta_eyebrow:"Let's work together", abp_cta_t:"Experience the Dar Mama difference",
    abp_cta_sub:"Get a free revenue estimate and see your future owner platform.",
    abp_cta_b1:"Get started", abp_cta_b2:"See the platform",
    /* contact page */
    ctp_eyebrow:"Let's talk", ctp_h1:"Get a free revenue estimate",
    ctp_sub:"Tell us about your property and we'll come back with a data-backed projection — and a tour of your future owner platform. No obligation.",
    ctp_form_t:"Request your estimate", ctp_form_sub:"We reply within one business day.",
    ctp_l_name:"Full name", ctp_l_email:"Email", ctp_l_area:"Area / building", ctp_l_bed:"Bedrooms",
    ctp_opt_sel:"Select", ctp_opt_studio:"Studio", ctp_opt_1:"1 bedroom", ctp_opt_2:"2 bedrooms", ctp_opt_3:"3 bedrooms", ctp_opt_4:"4+ bedrooms",
    ctp_l_msg:"Anything else?", ctp_ph_msg:"Tell us about your property and goals.", ctp_ph_area:"e.g. Dubai Marina",
    ctp_submit:"Send my request", ctp_prefer:"Prefer to chat?", ctp_prefer_link:"Message us on WhatsApp",
    ctp_info_eyebrow:"Reach us directly", ctp_info_t:"We're available the way you prefer",
    ctp_info_p:"We believe in personalised communication — including being on the platform you actually use.",
    ctp_wa:"WhatsApp", ctp_phone:"Phone", ctp_email:"Email", ctp_loc:"Location", ctp_loc_v:"Dubai, United Arab Emirates",
    ctp_owner_q:"Already an owner?", ctp_owner_link:"Log in to your platform",
    /* check-in: common + home promo + services callout */
    nav_checkin:"Check-in", nav_blog:"Blog", foot_checkin:"Check-in service", foot_blog:"Blog & guides", trust_label:"We list your property on",
    h_ci_eyebrow:"Standalone service",
    h_ci_title:"Need check-in only? We've got Dubai covered, 24/7.",
    h_ci_sub:"Self-managing your apartment, or running a holiday home? Use our physical check-in service on its own — unlimited 24/7 check-ins for a flat 500 AED/month per apartment.",
    h_ci_cta:"Discover the check-in service",
    sv_ci_eyebrow:"Standalone service", sv_ci_title:"Check-in service — even if we don't manage your property",
    sv_ci_p:"Self-managing owners and other holiday homes use our physical check-in service on its own: unlimited 24/7 check-ins for a flat 500 AED per apartment per month. A professional local team greets every guest, so you get peace of mind and better reviews.",
    sv_ci_cta:"See the check-in service",
    /* check-in page */
    cip_eyebrow:"Check-in service · Dubai · 24/7", cip_h1:"Professional 24/7 check-ins for your Dubai property",
    cip_sub:"A standalone service for owners who self-manage their apartment — and for holiday-home operators who want a reliable local team to greet every guest. Unlimited physical check-ins, day or night.",
    cip_cta1:"Get started", cip_cta2:"Ask on WhatsApp",
    cip_who_eyebrow:"Who it's for", cip_who_title:"Two kinds of clients, one reliable team",
    cip_w1_t:"Self-managing owners", cip_w1_b:"You handle your own listing and guests, but you can't always be there to hand over the keys. We become your on-the-ground check-in team — so you keep control and lose the hassle.",
    cip_w2_t:"Holiday homes & operators", cip_w2_b:"Other management companies trust us with their check-ins when their own team is stretched. Reliable coverage, a professional greeting, happier guests — without growing your headcount.",
    cip_inc_eyebrow:"What's included", cip_inc_title:"Everything a great arrival needs",
    cip_i1_t:"Unlimited check-ins", cip_i1_b:"As many guest arrivals as you have, every month — no per-check-in fees, no surprises.",
    cip_i2_t:"24/7 availability", cip_i2_b:"Early morning or late night, our team is there to welcome guests whenever they land.",
    cip_i3_t:"Warm meet & greet", cip_i3_b:"A real person greets your guests, hands over the keys and makes them feel at home from minute one.",
    cip_i4_t:"Property orientation", cip_i4_b:"We show guests around — Wi-Fi, appliances, house rules and local tips — so you get fewer questions later.",
    cip_i5_t:"Key handover & security", cip_i5_b:"Secure key management and ID verification at arrival, handled to hotel standards.",
    cip_i6_t:"Happier guests, better reviews", cip_i6_b:"Guests greeted in person leave better reviews — protecting your rating and your bookings.",
    cip_price_eyebrow:"Simple pricing", cip_price_title:"One flat monthly price. Unlimited check-ins.",
    cip_price_amount:"500 AED", cip_price_period:"per apartment / month",
    cip_price_li1:"Unlimited physical check-ins", cip_price_li2:"24/7 availability, every day",
    cip_price_li3:"Meet & greet, orientation, key handover", cip_price_li4:"No setup fee, no per-check-in charge",
    cip_price_cta:"Start your check-in service",
    cip_tm_eyebrow:"Trusted by other operators",
    cip_tm_q:"\"Dar Mama check-in service is the best! We have peace of mind and can relax at check-in time, and guests are happier when there is someone to greet them and show them around.\"",
    cip_tm_who:"— Hollybush Holiday Homes",
    cip_cta_eyebrow:"Ready to hand over check-ins?", cip_cta_t:"Let our team welcome your guests",
    cip_cta_sub:"500 AED per apartment per month, unlimited 24/7 check-ins. Tell us how many units you have.",
    cip_cta_b1:"Get started", cip_cta_b2:"WhatsApp us"
  },
  fr: {
    nav_home:"Accueil", nav_platform:"Espace propriétaire", nav_services:"Services", nav_about:"À propos", nav_contact:"Contact",
    nav_login:"Connexion", nav_estimate:"Estimation gratuite",
    foot_about:"L'hospitalité avec le sens du détail. Gestion locative courte durée transparente à Dubaï, avec une plateforme en temps réel pensée pour les propriétaires.",
    foot_h_company:"Société", foot_h_owners:"Propriétaires", foot_h_contact:"Contact",
    foot_about_us:"À propos", foot_services:"Services", foot_platform:"Espace propriétaire", foot_contact:"Contact",
    foot_estimate:"Estimation gratuite", foot_login:"Connexion propriétaire", foot_how:"Le fonctionnement de la plateforme",
    foot_rights:"© 2026 Dar Mama. Tous droits réservés.", foot_loc:"Dubaï, Émirats arabes unis · Licence holiday homes DET (ex-DTCM)",
    wa_chat:"Discuter",
    h_eyebrow:"Gestion locative courte durée · Dubaï",
    h_h1:'Vous êtes propriétaire.<br><span class="accent">Voyez</span> la performance.',
    h_sub:"Dar Mama gère votre location courte durée à Dubaï de A à Z — sans aucun tracas pour vous — et vous donne une plateforme propriétaire en temps réel pour suivre chaque réservation, chaque dirham, chaque versement. L'hospitalité avec soin, gérée comme un hôtel.",
    h_cta1:"Obtenir une estimation gratuite", h_cta2:"Voir la plateforme propriétaire",
    h_trust_s1:"Superhost · 2 ans", h_trust_s2:"Commission transparente", h_trust_s3:"Holiday homes agréées",
    h_sv_eyebrow:"Ce que nous faisons", h_sv_title:"Gestion complète, revenus maximisés",
    h_sv_lead:"De la mise en ligne et la tarification aux check-ins, au ménage et à la maintenance — nous gérons votre bien comme un actif, pas comme un à-côté.",
    h_c1_t:"Revenue management", h_c1_b:"Une tarification dynamique et pilotée par la donnée, comme à l'hôtel — nous optimisons l'occupation et l'ADR pour augmenter votre RevPAR, pas seulement le volume.",
    h_c2_t:"Gestion complète du bien", h_c2_b:"Annonces, réservations, sélection des voyageurs, check-in et check-out, ménage, linge et maintenance — tout est pris en charge, vous ne touchez à rien.",
    h_c3_t:"Service client personnalisé", h_c3_b:"Communication multilingue 24/7 sur le canal préféré des voyageurs, dont WhatsApp, avec notre équipe qui assure les check-ins en personne dès que nécessaire.",
    h_c4_t:"Finances transparentes", h_c4_b:"Une commission claire de 17 % sur votre revenu net, et un relevé mensuel détaillant le brut, les frais OTA, le ménage, la taxe de séjour et votre versement net. Jamais de surprise.",
    h_c5_t:"Maintenance & entretien", h_c5_b:"Nous maintenons votre bien en parfait état avec des artisans de confiance et documentons les interventions — pour protéger votre actif et vos avis.",
    h_c6_t:"Licence & conformité", h_c6_b:"Nous vous accompagnons sur l'enregistrement DET (ex-DTCM) et la conformité, pour une location légale et sereine.",
    h_op_eyebrow:"La différence Dar Mama", h_op_title:"Le seul gestionnaire à Dubaï qui vous montre tout, en direct.",
    h_op_sub:"La plupart des propriétaires confient leurs clés puis attendent un e-mail mensuel vague. Avec Dar Mama, vous avez une plateforme sécurisée — les chiffres exacts sur lesquels nous travaillons, accessibles 24/7.",
    h_op_li0:"Nous nous occupons de tout — zéro tracas pour vous",
    h_op_li1:"Occupation, ADR, RevPAR et revenus en temps réel par bien",
    h_op_li2:"Relevés mensuels détaillés ligne par ligne et votre versement net exact",
    h_op_li3:"Réservations passées, en cours et à venir en un coup d'œil",
    h_op_li4:"Vos documents, licences et factures dans un coffre sécurisé",
    h_op_li5:"Bilingue, ordinateur et mobile, accessible partout",
    h_op_cta1:"Explorer la plateforme", h_op_cta2:"Connexion propriétaire",
    h_hw_eyebrow:"Comment ça marche", h_hw_title:"Des clés aux versements en quatre étapes",
    h_hw1_t:"Estimation gratuite", h_hw1_b:"Indiquez votre bien et son quartier. Nous envoyons une projection de revenus chiffrée — sans engagement.",
    h_hw2_t:"Mise en route", h_hw2_b:"Nous photographions, mettons en ligne, tarifons et déclarons votre bien, et créons votre compte propriétaire.",
    h_hw3_t:"Nous opérons", h_hw3_b:"Réservations, voyageurs, ménage et maintenance tournent en autonomie, optimisés chaque jour.",
    h_hw4_t:"Vous êtes payé", h_hw4_b:"Suivez tout en direct et recevez un relevé clair et votre versement chaque mois.",
    h_st1:"Support voyageurs", h_st2:"Note Superhost", h_st3:"Reporting propriétaire", h_st4:"Commission, tout compris",
    h_tm_eyebrow:"Ils nous font confiance",
    h_tm_q:"« Pour la première fois je vois vraiment ce que fait mon appartement — réservations, revenus, versements, au même endroit. C'est comme avoir une équipe d'hôtel et un service financier dans ma poche. »",
    h_tm_who:"— David, propriétaire Dar Mama, Downtown Dubai",
    h_faq_eyebrow:"FAQ", h_faq_title:"Les questions des propriétaires",
    h_q1:"Combien puis-je gagner en louant mon appartement à Dubaï ?",
    h_a1:"Cela dépend du quartier, de la taille et du standing de votre bien. Nous fournissons une estimation gratuite et chiffrée, basée sur la performance réelle de biens comparables dans votre immeuble ou quartier.",
    h_q2:"Quels sont les tarifs de Dar Mama ?",
    h_a2:"Une commission simple et transparente de 17 % — et uniquement sur votre revenu NET. Le « net » correspond à ce qui reste une fois déduits du montant brut de la réservation la commission de la plateforme, les frais de ménage et la taxe de séjour de Dubaï. Nos 17 % s'appliquent à cette base nette, et chaque ligne figure dans votre relevé mensuel, pour que vous voyiez exactement comment se construit votre versement.",
    h_q3:"Puis-je suivre la performance de mon bien en temps réel ?",
    h_a3:"Oui. Chaque propriétaire dispose d'un accès sécurisé à la plateforme Dar Mama : occupation, ADR, RevPAR, revenus, relevés et documents en direct.",
    h_q4:"Gérez-vous la licence holiday home à Dubaï ?",
    h_a4:"Oui. Nous vous accompagnons sur l'enregistrement DET (ex-DTCM) et gérons la conformité opérationnelle pour une location légale.",
    h_cta_eyebrow:"Quand vous voulez", h_cta_title:"Découvrez ce que votre bien peut rapporter",
    h_cta_sub:"Obtenez une estimation gratuite et sans engagement, et une démo de la plateforme.",
    h_cta_b1:"Obtenir mon estimation", h_cta_b2:"Nous écrire sur WhatsApp",
    opp_eyebrow:"Votre bien, en temps réel", opp_h1:"La plateforme qui rend la gestion transparente",
    opp_sub:"Les autres gestionnaires envoient un e-mail vague une fois par mois. Dar Mama vous donne un accès sécurisé au tableau de bord exact sur lequel nous travaillons — performance en direct, relevés et documents, sur ordinateur et mobile.",
    opp_login:"Connexion propriétaire", opp_become:"Devenir client",
    opp_eyebrow2:"Conçu pour le revenue management", opp_t2:"Les chiffres que nous optimisons — visibles par vous",
    opp_p2:"Nous gérons votre bien avec un revenue management de niveau hôtelier : occupation, ADR et RevPAR suivis chaque jour. La plateforme affiche ces KPI exacts, pour que vous sachiez toujours comment performe votre actif — et voyiez le résultat de chaque décision de prix.",
    opp_li1:"Occupation, ADR et RevPAR avec variations mensuelles et annuelles",
    opp_li2:"Revenus par canal — Airbnb, Booking.com, Expedia, direct",
    opp_li3:"Prévisions et saisonnalité, pour éviter les surprises",
    opp_inside_eyebrow:"Ce qu'elle contient", opp_inside_title:"Tout ce dont un propriétaire a besoin, au même endroit",
    opp_f1_t:"Performance en direct", opp_f1_b:"Occupation, ADR, RevPAR, revenus brut et net, mis à jour depuis vos réservations — par bien et sur tout le portefeuille.",
    opp_f2_t:"Relevés mensuels", opp_f2_b:"Chaque ligne : brut, commission OTA, ménage, taxe de séjour, notre commission de 17 % et votre versement net exact. Téléchargeable en PDF.",
    opp_f3_t:"Réservations", opp_f3_b:"Séjours passés, en cours et à venir, canaux, nuits et avis voyageurs — avec un calendrier mensuel clair.",
    opp_f4_t:"Historique des versements", opp_f4_b:"Voyez ce qui a été payé et ce qui arrive, avec un historique transparent de chaque virement.",
    opp_f5_t:"Coffre à documents", opp_f5_b:"Licences, contrats, factures et rapports stockés en sécurité et accessibles à tout moment.",
    opp_f6_t:"Privé & sécurisé", opp_f6_b:"Vous ne voyez que vos biens. Contrôle d'accès de niveau bancaire, double authentification et données chiffrées.",
    opp_why_eyebrow:"Pourquoi c'est important", opp_why_title:"La transparence, c'est la différence entre un gestionnaire et un partenaire",
    opp_why_p:"Quand vous voyez tout, la confiance n'est plus une promesse — c'est un tableau de bord. Plus besoin de relancer, plus de relevés opaques, plus de doute sur où va votre argent. Juste des chiffres clairs, consultables à tout moment, partout.",
    opp_why_li1:"Pensé ordinateur, parfait sur mobile, installable comme une app",
    opp_why_li2:"Interface bilingue, devise en AED",
    opp_why_li3:"Une seule connexion pour tout votre portefeuille",
    opp_why_b1:"Commencer", opp_why_b2:"Voir nos services",
    opp_panel_big:"Live", opp_panel_small:"Votre tableau de bord, sur tous vos écrans",
    opp_cta_eyebrow:"Déjà client ?", opp_cta_title:"Connectez-vous à votre plateforme",
    opp_cta_sub:"Accédez à votre tableau de bord, vos relevés et documents.",
    opp_cta_b1:"Connexion propriétaire", opp_cta_b2:"Nous contacter",
    svp_eyebrow:"Gestion clé en main · Dubaï", svp_h1:"Tout ce dont votre location a besoin — pris en charge",
    svp_sub:"Un seul partenaire pour les revenus, l'exploitation, les voyageurs et la conformité. Vous gardez la propriété et une visibilité totale ; nous faisons le travail. Zéro tracas.",
    svp_cta1:"Obtenir une estimation gratuite",
    svp_c1_t:"Revenue management", svp_c1_b:"Tarification de niveau hôtelier, pilotée par la donnée. Nous ajustons les prix chaque jour selon la saison, la demande, les événements et la concurrence pour maximiser le RevPAR — l'équilibre occupation/prix — pas seulement remplir à bas prix.",
    svp_c2_t:"Annonces & distribution", svp_c2_b:"Annonces professionnelles sur Airbnb, Booking.com, Expedia et en direct, avec photos de qualité, textes optimisés et calendriers synchronisés pour éviter les doublons.",
    svp_c3_t:"Expérience voyageur", svp_c3_b:"Communication multilingue 24/7, sélection, check-in et check-out fluides et suivi pendant le séjour — notre équipe assure les check-ins en personne dès que nécessaire. De beaux séjours, d'excellents avis.",
    svp_c4_t:"Ménage & linge", svp_c4_b:"Ménage aux standards hôteliers, linge frais et équipements entre chaque séjour, avec contrôles qualité pour un bien toujours prêt.",
    svp_c5_t:"Maintenance & entretien", svp_c5_b:"Maintenance proactive avec des artisans de confiance, documentée avant/après, pour protéger votre actif et éviter les mauvais avis.",
    svp_c6_t:"Licence & conformité", svp_c6_b:"Accompagnement sur l'enregistrement DET (ex-DTCM) et la conformité continue, pour une location légale et sûre.",
    svp_c7_t:"Finances transparentes", svp_c7_b:"Une commission claire de 17 % sur le revenu net, avec relevés mensuels et versements à l'heure — chaque frais détaillé sur votre plateforme. Aucun frais caché.",
    svp_c8_t:"Reporting propriétaire", svp_c8_b:"Votre tableau de bord en temps réel : occupation, ADR, RevPAR, revenus, relevés et documents — ce que les concurrents n'offrent pas.",
    svp_rm_eyebrow:"Pourquoi le revenue management compte", svp_rm_t:"Nous gérons votre appartement comme un hôtel gère une chambre",
    svp_rm_p:"La plupart des propriétaires — et beaucoup de gestionnaires — fixent un prix et l'oublient. Nous traitons chaque nuit comme un stock à vendre au bon prix. En optimisant occupation et ADR ensemble, nous augmentons le RevPAR, l'indicateur qui reflète vraiment le rendement de votre actif.",
    svp_rm_li1:"Tarification dynamique quotidienne selon la demande, la saison et les événements",
    svp_rm_li2:"Stratégies de durée de séjour et de nuits minimum",
    svp_rm_li3:"Optimisation du mix de canaux pour réduire les frais OTA",
    svp_rm_li4:"Prévisions pour anticiper la saisonnalité",
    svp_cta_eyebrow:"Parlons chiffres", svp_cta_t:"Combien votre bien peut-il rapporter avec Dar Mama ?",
    svp_cta_sub:"Estimation gratuite et sans engagement, basée sur des données réelles de biens comparables à Dubaï.",
    svp_cta_b1:"Obtenir mon estimation", svp_cta_b2:"Voir la plateforme",
    abp_eyebrow:"L'hospitalité avec le sens du détail", abp_h1:"Embrace the mama",
    abp_sub:"Nous ne faisons pas que gérer des biens. Nous créons des moments de confort et de luxe pour vos voyageurs, et traitons votre actif — et votre confiance — avec le soin qu'ils méritent.",
    abp_story_eyebrow:"Notre histoire", abp_story_t:"Le soin d'un hôte, la rigueur d'un gestionnaire",
    abp_story_p1:"Dar Mama est née d'une conviction simple : les propriétaires méritent à la fois la tranquillité d'esprit et la vérité. Le marché de Dubaï est compétitif et rapide, et trop de propriétaires confient leurs clés pour ne recevoir que des nouvelles vagues et des relevés opaques.",
    abp_story_p2:"Nous avons conçu Dar Mama différemment — en associant une hospitalité chaleureuse et attentive à la rigueur d'un revenue management hôtelier, le tout adossé à ce que presque aucun concurrent n'offre : une plateforme en temps réel où vous voyez exactement comment performe votre bien, à tout moment.",
    abp_panel_big:"4,97★", abp_panel_small:"Superhost · 2 ans sur Airbnb",
    abp_team_eyebrow:"Les fondateurs", abp_team_title:"Deux opérateurs, un même niveau d'exigence",
    abp_team_intro:"Dar Mama n'est pas une agence sans visage. Ce sont deux personnes qui ont passé leur carrière dans l'hôtellerie et ont décidé de le faire vraiment bien — pour des propriétaires comme vous.",
    abp_ismail_role:"Cofondateur · Commercial, Marketing & Revenue Management",
    abp_ismail_bio:"Ismail a passé 15 ans au sein des groupes hôteliers les plus exigeants — Marriott, Accor et Disney — à diriger des équipes commerciales, marketing et de revenue management. Il y a appris comment les grands hôtels transforment la donnée en juste prix au bon moment, et ce qu'est vraiment un service d'exception. Il a fondé Dar Mama pour apporter cette rigueur aux propriétaires particuliers : chaque appartement tarifé et géré comme une chambre d'hôtel, chaque décision appuyée par des chiffres que vous pouvez réellement voir.",
    abp_dounia_role:"Cofondatrice · Customer Success & Opérations",
    abp_dounia_bio:"Dounia vit à Dubaï depuis 12 ans, où elle a bâti sa carrière dans le customer success et les opérations de terrain. Elle a piloté d'innombrables chantiers de rénovation et de mise à niveau — transformant des appartements fatigués en logements que les voyageurs adorent et dont les propriétaires sont fiers. Chaleureuse avec les voyageurs et intransigeante sur le détail, elle veille à ce que chaque bien Dar Mama soit au meilleur de sa forme, séjour après séjour.",
    abp_commit_eyebrow:"Nos valeurs", abp_commit_title:"Notre engagement envers les propriétaires",
    abp_c1_t:"Transparence totale", abp_c1_b:"Vous voyez les mêmes chiffres que nous. Chaque réservation, frais et versement est visible sur votre plateforme — aucune boîte noire.",
    abp_c2_t:"Un vrai soin", abp_c2_b:"Chaque voyageur est unique, chaque propriétaire aussi. Nous offrons une attention personnalisée qui génère d'excellents avis et une confiance durable.",
    abp_c3_t:"Excellence hôtelière", abp_c3_b:"Nous sommes votre partenaire pour créer des séjours d'exception — en protégeant à la fois votre réputation et vos revenus.",
    abp_q:"« Votre réussite est la nôtre — et nous sommes là pour la rendre extraordinaire. »", abp_q_who:"— L'équipe Dar Mama",
    abp_cta_eyebrow:"Travaillons ensemble", abp_cta_t:"Découvrez la différence Dar Mama",
    abp_cta_sub:"Obtenez une estimation gratuite et découvrez votre future plateforme.",
    abp_cta_b1:"Commencer", abp_cta_b2:"Voir la plateforme",
    ctp_eyebrow:"Parlons-en", ctp_h1:"Obtenez une estimation gratuite",
    ctp_sub:"Parlez-nous de votre bien et nous reviendrons avec une projection chiffrée — et une démo de votre future plateforme. Sans engagement.",
    ctp_form_t:"Demandez votre estimation", ctp_form_sub:"Nous répondons sous un jour ouvré.",
    ctp_l_name:"Nom complet", ctp_l_email:"E-mail", ctp_l_area:"Quartier / immeuble", ctp_l_bed:"Chambres",
    ctp_opt_sel:"Sélectionner", ctp_opt_studio:"Studio", ctp_opt_1:"1 chambre", ctp_opt_2:"2 chambres", ctp_opt_3:"3 chambres", ctp_opt_4:"4+ chambres",
    ctp_l_msg:"Autre chose ?", ctp_ph_msg:"Parlez-nous de votre bien et de vos objectifs.", ctp_ph_area:"ex. Dubai Marina",
    ctp_submit:"Envoyer ma demande", ctp_prefer:"Vous préférez discuter ?", ctp_prefer_link:"Écrivez-nous sur WhatsApp",
    ctp_info_eyebrow:"Contactez-nous directement", ctp_info_t:"Disponibles comme vous le préférez",
    ctp_info_p:"Nous croyons à une communication personnalisée — y compris sur le canal que vous utilisez vraiment.",
    ctp_wa:"WhatsApp", ctp_phone:"Téléphone", ctp_email:"E-mail", ctp_loc:"Localisation", ctp_loc_v:"Dubaï, Émirats arabes unis",
    ctp_owner_q:"Déjà client ?", ctp_owner_link:"Connectez-vous à votre plateforme",
    nav_checkin:"Check-in", nav_blog:"Blog", foot_checkin:"Service de check-in", foot_blog:"Blog & guides", trust_label:"Nous publions votre bien sur",
    h_ci_eyebrow:"Service à la carte",
    h_ci_title:"Besoin du check-in uniquement ? On couvre Dubaï, 24/7.",
    h_ci_sub:"Vous gérez vous-même votre appartement, ou vous exploitez une holiday home ? Utilisez notre service de check-in physique seul — check-ins illimités 24/7 pour 500 AED/mois par appartement, forfait fixe.",
    h_ci_cta:"Découvrir le service de check-in",
    sv_ci_eyebrow:"Service à la carte", sv_ci_title:"Service de check-in — même si nous ne gérons pas votre bien",
    sv_ci_p:"Les propriétaires autonomes et d'autres holiday homes utilisent notre service de check-in physique seul : check-ins illimités 24/7 pour 500 AED par appartement et par mois, forfait fixe. Une équipe locale professionnelle accueille chaque voyageur — tranquillité d'esprit et meilleurs avis.",
    sv_ci_cta:"Voir le service de check-in",
    cip_eyebrow:"Service de check-in · Dubaï · 24/7", cip_h1:"Des check-ins professionnels 24/7 pour votre bien à Dubaï",
    cip_sub:"Un service à la carte pour les propriétaires qui gèrent eux-mêmes leur appartement — et pour les holiday homes qui veulent une équipe locale fiable pour accueillir chaque voyageur. Check-ins physiques illimités, jour et nuit.",
    cip_cta1:"Commencer", cip_cta2:"Demander sur WhatsApp",
    cip_who_eyebrow:"Pour qui", cip_who_title:"Deux types de clients, une équipe fiable",
    cip_w1_t:"Propriétaires autonomes", cip_w1_b:"Vous gérez votre annonce et vos voyageurs, mais vous ne pouvez pas toujours être là pour remettre les clés. Nous devenons votre équipe de check-in sur place — vous gardez le contrôle, sans la contrainte.",
    cip_w2_t:"Holiday homes & exploitants", cip_w2_b:"D'autres sociétés de gestion nous confient leurs check-ins quand leur équipe est sous tension. Une couverture fiable, un accueil professionnel, des voyageurs plus satisfaits — sans recruter.",
    cip_inc_eyebrow:"Ce qui est inclus", cip_inc_title:"Tout ce qu'une belle arrivée exige",
    cip_i1_t:"Check-ins illimités", cip_i1_b:"Autant d'arrivées que vous avez, chaque mois — aucun frais par check-in, aucune surprise.",
    cip_i2_t:"Disponibilité 24/7", cip_i2_b:"Tôt le matin ou tard le soir, notre équipe est là pour accueillir les voyageurs à toute heure.",
    cip_i3_t:"Accueil chaleureux", cip_i3_b:"Une vraie personne accueille vos voyageurs, remet les clés et les met à l'aise dès la première minute.",
    cip_i4_t:"Présentation du logement", cip_i4_b:"Nous faisons le tour du logement — Wi-Fi, équipements, règles et bons plans — pour vous éviter des questions ensuite.",
    cip_i5_t:"Remise des clés & sécurité", cip_i5_b:"Gestion sécurisée des clés et vérification d'identité à l'arrivée, aux standards hôteliers.",
    cip_i6_t:"Voyageurs ravis, meilleurs avis", cip_i6_b:"Des voyageurs accueillis en personne laissent de meilleurs avis — ce qui protège votre note et vos réservations.",
    cip_price_eyebrow:"Tarif simple", cip_price_title:"Un tarif mensuel fixe. Check-ins illimités.",
    cip_price_amount:"500 AED", cip_price_period:"par appartement / mois",
    cip_price_li1:"Check-ins physiques illimités", cip_price_li2:"Disponibilité 24/7, tous les jours",
    cip_price_li3:"Accueil, présentation, remise des clés", cip_price_li4:"Sans frais d'installation, sans frais par check-in",
    cip_price_cta:"Démarrer votre service de check-in",
    cip_tm_eyebrow:"La confiance d'autres exploitants",
    cip_tm_q:"« Le service de check-in de Dar Mama est le meilleur ! Nous avons l'esprit tranquille et pouvons nous détendre au moment du check-in, et les voyageurs sont plus heureux quand quelqu'un les accueille et leur fait visiter. »",
    cip_tm_who:"— Hollybush Holiday Homes",
    cip_cta_eyebrow:"Prêt à déléguer vos check-ins ?", cip_cta_t:"Laissez notre équipe accueillir vos voyageurs",
    cip_cta_sub:"500 AED par appartement et par mois, check-ins illimités 24/7. Dites-nous combien d'appartements vous avez.",
    cip_cta_b1:"Commencer", cip_cta_b2:"Nous écrire sur WhatsApp"
  }
};

function applyLang(lang){
  if(!DICT[lang]) lang = "en";
  var d = DICT[lang];
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach(function(el){
    var v = d[el.getAttribute("data-i18n")];
    if(v != null) el.innerHTML = v;
  });
  document.querySelectorAll("[data-i18n-ph]").forEach(function(el){
    var v = d[el.getAttribute("data-i18n-ph")];
    if(v != null) el.setAttribute("placeholder", v);
  });
  document.querySelectorAll(".lang-switch button").forEach(function(b){
    b.classList.toggle("active", b.getAttribute("data-lang") === lang);
  });
  try { localStorage.setItem("darmama_lang", lang); } catch(e){}
}

(function(){
  var saved = "en";
  try { saved = localStorage.getItem("darmama_lang") || "en"; } catch(e){}
  document.addEventListener("DOMContentLoaded", function(){
    applyLang(saved);
    document.querySelectorAll(".lang-switch button").forEach(function(b){
      b.addEventListener("click", function(){ applyLang(b.getAttribute("data-lang")); });
    });
    var toggle = document.querySelector(".menu-toggle");
    var links = document.querySelector(".nav-links");
    if(toggle && links){ toggle.addEventListener("click", function(){ links.classList.toggle("open"); }); }

    var form = document.querySelector("form[data-mailto]");
    if(form){
      form.addEventListener("submit", function(e){
        e.preventDefault();
        var fd = new FormData(form);
        var subject = encodeURIComponent("Property owner enquiry — " + ((fd.get("name")||"Dar Mama")));
        var body = encodeURIComponent(
          "Name: " + (fd.get("name")||"") + "\n" +
          "Email: " + (fd.get("email")||"") + "\n" +
          "Area: " + (fd.get("area")||"") + "\n" +
          "Bedrooms: " + (fd.get("bedrooms")||"") + "\n\n" +
          (fd.get("message")||"")
        );
        window.location.href = "mailto:contact@dar-mama.com?subject=" + subject + "&body=" + body;
      });
    }
  });
})();
